package com.rest.consumer.demo.error;


import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.client.HttpStatusCodeException;

import javax.xml.bind.ValidationException;

@ControllerAdvice
public class ErrorControllerAdvice {


    /**
     * Method to catch exception and return the defined response
     * Added as part of Exception handling changes.
     */
    @ExceptionHandler(HttpStatusCodeException.class)
    @ResponseStatus(value= HttpStatus.NOT_FOUND,reason="Friend not found")
    public ErrorMessage notFound(Exception ve) {
        return new ErrorMessage("400", ve.getMessage() +ve.getClass());
    }

    /**
     * This method is used to handle the exception generated by create() method.
     * @param ve
     * @return ErrorMessage
     */
    @ResponseBody
    @ResponseStatus(HttpStatus.NOT_FOUND)
    @ExceptionHandler
    ErrorMessage exeptionHandler(ValidationException ve){
        return new ErrorMessage("400", ve.getMessage());
    }
}
